// Industry-specific AI report section definitions
// Each industry has 6 section cards shown in the Reports Hub

export type IndustryId = 'solar' | 'insurance' | 'construction' | 'utilities' | 'telecom';

export interface ReportSection {
    id: string;
    title: string;
    description: string;
    icon: string; // emoji icon
    accent: string; // tailwind color name for theming
    accentHex: string;
    badge: string;
    generator: string; // which generator handles this section
}

export interface IndustryReportConfig {
    id: IndustryId;
    label: string;
    icon: string;
    color: string;
    colorHex: string;
    subtitle: string;
    sections: ReportSection[];
}

export const INDUSTRY_REPORT_CONFIGS: IndustryReportConfig[] = [
    {
        id: 'solar',
        label: 'Solar',
        icon: '☀️',
        color: 'amber',
        colorHex: '#f59e0b',
        subtitle: 'Solar AI Inspection Reports',
        sections: [
            {
                id: 'panel-degradation',
                title: 'Panel Degradation Analysis',
                description: 'Thermal anomaly detection, micro-crack identification, soiling index',
                icon: '🔥',
                accent: 'teal',
                accentHex: '#14b8a6',
                badge: 'Thermal AI',
                generator: 'solar',
            },
            {
                id: 'string-performance',
                title: 'String Performance Report',
                description: 'IV curve analysis, underperforming strings, production loss estimate',
                icon: '📈',
                accent: 'purple',
                accentHex: '#a855f7',
                badge: 'Performance AI',
                generator: 'solar',
            },
            {
                id: 'site-aerial',
                title: 'Site Overview & Aerial Map',
                description: 'Site boundary survey, obstruction detection, shading analysis',
                icon: '🗺️',
                accent: 'blue',
                accentHex: '#3b82f6',
                badge: 'Mapping AI',
                generator: 'solar',
            },
            {
                id: 'inverter-bos',
                title: 'Inverter & BOS Inspection',
                description: 'Combiner box condition, wiring anomalies, grounding check',
                icon: '⚡',
                accent: 'orange',
                accentHex: '#f97316',
                badge: 'Electrical AI',
                generator: 'solar',
            },
            {
                id: 'maintenance-matrix',
                title: 'Maintenance Priority Matrix',
                description: 'ROI-ranked punch list, recommended repair sequence',
                icon: '📋',
                accent: 'green',
                accentHex: '#22c55e',
                badge: 'Priority AI',
                generator: 'solar',
            },
            {
                id: 'solar-executive',
                title: 'Executive Summary Export',
                description: 'Branded portfolio-level PDF for site owners and investors',
                icon: '📄',
                accent: 'indigo',
                accentHex: '#6366f1',
                badge: 'PDF Export',
                generator: 'solar',
            },
        ],
    },
    {
        id: 'insurance',
        label: 'Insurance',
        icon: '🏠',
        color: 'red',
        colorHex: '#ef4444',
        subtitle: 'Insurance Claims AI Reports',
        sections: [
            {
                id: 'roof-damage',
                title: 'Roof Damage Assessment',
                description: 'Hail, wind, missing shingles, impact points — AI-annotated imagery',
                icon: '🏚️',
                accent: 'red',
                accentHex: '#ef4444',
                badge: 'Damage AI',
                generator: 'insurance',
            },
            {
                id: 'property-loss',
                title: 'Property Loss Estimate',
                description: 'Xactimate-ready line items, cost ranges per finding',
                icon: '💰',
                accent: 'orange',
                accentHex: '#f97316',
                badge: 'Cost AI',
                generator: 'insurance',
            },
            {
                id: 'storm-correlation',
                title: 'Storm Event Correlation',
                description: 'Date-of-loss weather overlay, hail size data, wind speed mapping',
                icon: '⛈️',
                accent: 'purple',
                accentHex: '#a855f7',
                badge: 'Weather AI',
                generator: 'insurance',
            },
            {
                id: 'pre-existing',
                title: 'Pre-Existing vs New Damage',
                description: 'AI classification with confidence scoring per finding',
                icon: '🔍',
                accent: 'teal',
                accentHex: '#14b8a6',
                badge: 'Classification AI',
                generator: 'insurance',
            },
            {
                id: 'photo-evidence',
                title: 'Photo Evidence Package',
                description: 'GPS-tagged annotated image set organized by damage zone',
                icon: '📸',
                accent: 'blue',
                accentHex: '#3b82f6',
                badge: 'Evidence Pack',
                generator: 'insurance',
            },
            {
                id: 'adjuster-summary',
                title: 'Adjuster Summary Report',
                description: 'Carrier-ready executive narrative with full inspection PDF',
                icon: '📋',
                accent: 'green',
                accentHex: '#22c55e',
                badge: 'PDF Export',
                generator: 'insurance',
            },
        ],
    },
    {
        id: 'construction',
        label: 'Construction',
        icon: '🏗️',
        color: 'yellow',
        colorHex: '#eab308',
        subtitle: 'Construction Progress AI Reports',
        sections: [
            {
                id: 'progress-capture',
                title: 'Progress Capture Report',
                description: '% complete per zone vs approved plan, schedule variance',
                icon: '📊',
                accent: 'yellow',
                accentHex: '#eab308',
                badge: 'Progress AI',
                generator: 'construction',
            },
            {
                id: 'earthwork-grading',
                title: 'Earthwork & Grading Analysis',
                description: 'Cut/fill volume calculations, grade compliance check',
                icon: '⛏️',
                accent: 'orange',
                accentHex: '#f97316',
                badge: 'Volume AI',
                generator: 'construction',
            },
            {
                id: 'site-safety',
                title: 'Site Safety Audit',
                description: 'PPE detection, hazard zone identification, OSHA flag log',
                icon: '🦺',
                accent: 'red',
                accentHex: '#ef4444',
                badge: 'Safety AI',
                generator: 'construction',
            },
            {
                id: 'stockpile',
                title: 'Material Stockpile Estimate',
                description: 'Volume calculations from 3D point cloud imagery',
                icon: '🏔️',
                accent: 'teal',
                accentHex: '#14b8a6',
                badge: '3D AI',
                generator: 'construction',
            },
            {
                id: 'punch-list',
                title: 'AI Punch List Generator',
                description: 'AI-flagged deficiencies organized by trade and priority',
                icon: '✅',
                accent: 'blue',
                accentHex: '#3b82f6',
                badge: 'QA AI',
                generator: 'construction',
            },
            {
                id: 'owner-report',
                title: 'Owner Progress Report',
                description: 'Branded milestone summary PDF for developers and lenders',
                icon: '🏢',
                accent: 'indigo',
                accentHex: '#6366f1',
                badge: 'PDF Export',
                generator: 'construction',
            },
        ],
    },
    {
        id: 'utilities',
        label: 'Utilities',
        icon: '⚡',
        color: 'cyan',
        colorHex: '#06b6d4',
        subtitle: 'Utility Grid AI Inspection Reports',
        sections: [
            {
                id: 'line-inspection',
                title: 'Transmission Line Inspection',
                description: 'Conductor damage, sag measurement, vegetation encroachment',
                icon: '🔌',
                accent: 'cyan',
                accentHex: '#06b6d4',
                badge: 'Line AI',
                generator: 'utilities',
            },
            {
                id: 'substation-audit',
                title: 'Substation Asset Audit',
                description: 'Equipment condition scoring, thermal anomaly detection',
                icon: '🏭',
                accent: 'orange',
                accentHex: '#f97316',
                badge: 'Asset AI',
                generator: 'utilities',
            },
            {
                id: 'vegetation',
                title: 'Vegetation Management',
                description: 'Clearance zone mapping, priority trim areas, risk rating',
                icon: '🌿',
                accent: 'green',
                accentHex: '#22c55e',
                badge: 'Veg AI',
                generator: 'utilities',
            },
            {
                id: 'corrosion',
                title: 'Corrosion & Structure Report',
                description: 'Tower/pole rust index, concrete spalling, structural flags',
                icon: '🏗️',
                accent: 'red',
                accentHex: '#ef4444',
                badge: 'Structural AI',
                generator: 'utilities',
            },
            {
                id: 'outage-risk',
                title: 'Outage Risk Assessment',
                description: 'Risk-ranked asset priority list with failure probability scores',
                icon: '⚠️',
                accent: 'purple',
                accentHex: '#a855f7',
                badge: 'Risk AI',
                generator: 'utilities',
            },
            {
                id: 'regulatory-export',
                title: 'Regulatory Compliance Export',
                description: 'NERC/FERC-ready audit trail with full evidence package',
                icon: '📜',
                accent: 'indigo',
                accentHex: '#6366f1',
                badge: 'PDF Export',
                generator: 'utilities',
            },
        ],
    },
    {
        id: 'telecom',
        label: 'Telecom',
        icon: '📡',
        color: 'violet',
        colorHex: '#8b5cf6',
        subtitle: 'Telecom Tower AI Inspection Reports',
        sections: [
            {
                id: 'tower-structural',
                title: 'Tower Structural Report',
                description: 'Deformation detection, rust scoring, mount integrity check',
                icon: '📡',
                accent: 'violet',
                accentHex: '#8b5cf6',
                badge: 'Structural AI',
                generator: 'telecom',
            },
            {
                id: 'antenna-audit',
                title: 'Antenna & Equipment Audit',
                description: 'Azimuth verification, equipment ID, condition scoring',
                icon: '📶',
                accent: 'blue',
                accentHex: '#3b82f6',
                badge: 'RF AI',
                generator: 'telecom',
            },
            {
                id: 'cable-assessment',
                title: 'Cable & Line Assessment',
                description: 'Feeder cable routing check, weatherproofing condition',
                icon: '🔗',
                accent: 'teal',
                accentHex: '#14b8a6',
                badge: 'Cable AI',
                generator: 'telecom',
            },
            {
                id: 'faa-compliance',
                title: 'Lighting & FAA Compliance',
                description: 'Obstruction light operational check, FAA regulation flags',
                icon: '✈️',
                accent: 'red',
                accentHex: '#ef4444',
                badge: 'Compliance AI',
                generator: 'telecom',
            },
            {
                id: 'climb-hazard',
                title: 'Climb Hazard Log',
                description: 'Anchor point condition, platform integrity, fall protection',
                icon: '🧗',
                accent: 'orange',
                accentHex: '#f97316',
                badge: 'Safety AI',
                generator: 'telecom',
            },
            {
                id: 'carrier-report',
                title: 'Carrier Delivery Report',
                description: 'Branded tower audit PDF package for carrier submission',
                icon: '📋',
                accent: 'green',
                accentHex: '#22c55e',
                badge: 'PDF Export',
                generator: 'telecom',
            },
        ],
    },
];

export const getIndustryConfig = (id: IndustryId): IndustryReportConfig | undefined =>
    INDUSTRY_REPORT_CONFIGS.find(c => c.id === id);
