import React, { useState } from 'react';
import { FileText, Download, CheckCircle2, Send, Loader2, Sparkles, Clock, Calendar } from 'lucide-react';
import apiClient from '../../../src/services/apiClient';

export default function SameDayReportWorkflow({ projectId, reports, onReportGenerated }) {
    const [generating, setGenerating] = useState(false);
    const [reportStatus, setReportStatus] = useState('none'); // none, drafting, published
    const [summary, setSummary] = useState('');
    const [submitting, setSubmitting] = useState(false);

    const handleGenerate = async () => {
        setGenerating(true);
        try {
            // Actual API call to generate report draft
            const response = await apiClient.post(`/construction/projects/${projectId}/reports/generate`);
            if (response.data.success) {
                setSummary(response.data.data.executiveSummary || "AI Analysis complete. No significant updates detected for today.");
                setReportStatus('drafting');
            }
        } catch (error) {
            console.error('Failed to generate report', error);
            setSummary("An error occurred while generating the report draft from field observations.");
            setReportStatus('drafting');
        } finally {
            setGenerating(false);
        }
    };

    const handlePublish = async () => {
        setSubmitting(true);
        try {
            await apiClient.post(`/construction/projects/${projectId}/reports`, {
                reportDate: new Date().toISOString().split('T')[0],
                executiveSummary: summary
            });
            setReportStatus('published');
            onReportGenerated();
        } catch (error) {
            console.error('Failed to publish report', error);
        } finally {
            setSubmitting(false);
        }
    };

    const handleDownloadPDF = (report?: any) => {
        import('jspdf').then(({ default: jsPDF }) => {
            const doc = new jsPDF();
            
            // Header
            doc.setFillColor(15, 23, 42); // slate-900
            doc.rect(0, 0, 210, 40, 'F');
            
            doc.setTextColor(255, 255, 255);
            doc.setFontSize(22);
            doc.setFont('helvetica', 'bold');
            doc.text('AXIS CONSTRUCTION COMMAND', 105, 20, { align: 'center' });
            
            doc.setFontSize(10);
            doc.setFont('helvetica', 'normal');
            doc.setTextColor(148, 163, 184); // slate-400
            const reportDate = report ? new Date(report.report_date).toLocaleDateString() : new Date().toLocaleDateString();
            doc.text(`Same-Day Progress Report | ${reportDate}`, 105, 30, { align: 'center' });
            
            // Content
            doc.setTextColor(15, 23, 42); // slate-900
            doc.setFontSize(16);
            doc.setFont('helvetica', 'bold');
            doc.text('Executive Summary', 20, 60);
            
            doc.setFontSize(10);
            doc.setFont('helvetica', 'normal');
            doc.setTextColor(51, 65, 85); // slate-700
            
            const content = report ? report.executive_summary : summary;
            const splitContent = doc.splitTextToSize(content || 'No summary available.', 170);
            doc.text(splitContent, 20, 70);
            
            // Footer
            doc.setFontSize(8);
            doc.setTextColor(148, 163, 184);
            doc.text(`Generated by Axis Enterprise Platform | Project ID: ${projectId}`, 105, 285, { align: 'center' });
            
            doc.save(`Axis_Report_${reportDate.replace(/\//g, '-')}.pdf`);
        });
    };

    return (
        <div className="p-8 animate-fade-in text-slate-200">
            <h2 className="text-2xl font-black text-white tracking-tight mb-8 flex items-center gap-3">
                <FileText className="w-6 h-6 text-indigo-400" />
                Same-Day Reports
            </h2>
            
            {/* Previous Reports Section */}
            {reports && reports.length > 0 && (
                <div className="mb-10">
                    <h3 className="text-[11px] font-black text-slate-500 uppercase tracking-widest mb-4">Report Archive</h3>
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                        {reports.map((report: any) => (
                            <div key={report.id} className="bg-slate-800/40 border border-slate-700/50 p-5 rounded-2xl flex flex-col hover:bg-slate-800/60 transition-colors group cursor-pointer">
                                <div className="flex justify-between items-start mb-3">
                                    <div className="flex items-center gap-2">
                                        <Calendar className="w-4 h-4 text-slate-400" />
                                        <span className="text-sm font-bold text-white">{new Date(report.report_date).toLocaleDateString()}</span>
                                    </div>
                                    <span className={`text-[9px] font-black uppercase tracking-widest px-2 py-0.5 rounded border ${
                                        report.status === 'Published' ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30' : 'bg-yellow-500/10 text-yellow-400 border-yellow-500/30'
                                    }`}>
                                        {report.status}
                                    </span>
                                </div>
                                <p className="text-xs text-slate-400 line-clamp-3 mb-4 flex-1">{report.executive_summary}</p>
                                <button 
                                    onClick={() => handleDownloadPDF(report)}
                                    className="text-[10px] font-black text-indigo-400 uppercase tracking-widest flex items-center gap-1 group-hover:text-indigo-300 transition-colors mt-auto"
                                >
                                    <Download className="w-3 h-3" /> Download PDF
                                </button>
                            </div>
                        ))}
                    </div>
                </div>
            )}

            {/* Generation Flow */}
            <h3 className="text-[11px] font-black text-slate-500 uppercase tracking-widest mb-4">Generate New Report</h3>
            
            {reportStatus === 'none' && (
                <div className="bg-slate-900/40 border border-indigo-500/20 border-dashed rounded-3xl p-16 text-center max-w-3xl mx-auto relative group overflow-hidden">
                    <div className="absolute inset-0 bg-gradient-to-b from-indigo-500/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500"></div>
                    <div className="relative z-10">
                        <div className="w-20 h-20 bg-indigo-500/10 border border-indigo-500/30 rounded-full flex items-center justify-center mx-auto mb-6 shadow-[0_0_30px_rgba(99,102,241,0.1)]">
                            <Sparkles className="w-8 h-8 text-indigo-400" />
                        </div>
                        <h3 className="text-xl font-black text-white mb-3 tracking-tight">AI-Powered Daily Progress</h3>
                        <p className="text-sm text-slate-400 max-w-md mx-auto mb-8 leading-relaxed">
                            Aggregate today's drone imagery, field observations, and open issues into a structured, executive-ready progress report instantly.
                        </p>
                        <button 
                            onClick={handleGenerate}
                            disabled={generating}
                            className="bg-indigo-600 hover:bg-indigo-500 disabled:bg-slate-800 disabled:text-slate-500 text-white px-8 py-4 rounded-xl text-xs font-black uppercase tracking-widest shadow-[0_0_20px_rgba(79,70,229,0.3)] hover:shadow-[0_0_30px_rgba(79,70,229,0.5)] flex items-center justify-center gap-3 mx-auto w-64 transition-all"
                        >
                            {generating ? <Loader2 className="w-5 h-5 animate-spin" /> : <Sparkles className="w-5 h-5" />}
                            {generating ? 'Processing Data...' : 'Generate Draft'}
                        </button>
                    </div>
                </div>
            )}

            {reportStatus === 'drafting' && (
                <div className="bg-slate-900/60 backdrop-blur-xl border border-indigo-500/30 rounded-3xl p-8 shadow-2xl relative overflow-hidden animate-fade-in">
                    <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-indigo-500 to-purple-500"></div>
                    
                    <div className="flex items-center justify-between mb-8 pb-6 border-b border-slate-700/50">
                        <div>
                            <h3 className="text-xl font-black text-white tracking-tight flex items-center gap-3">
                                <Clock className="w-5 h-5 text-yellow-400" />
                                Review Draft Report
                            </h3>
                            <p className="text-xs text-slate-400 mt-1">Review and refine the AI-generated summary before publishing to stakeholders.</p>
                        </div>
                        <span className="bg-yellow-500/10 text-yellow-400 border border-yellow-500/30 px-3 py-1.5 rounded-lg text-[10px] font-black uppercase tracking-widest">Draft Mode</span>
                    </div>
                    
                    <div className="space-y-6 mb-8">
                        <div>
                            <label className="block text-[10px] font-black text-slate-400 uppercase tracking-widest mb-3">Executive Summary (Editable)</label>
                            <div className="relative">
                                <Sparkles className="absolute top-4 left-4 w-4 h-4 text-indigo-500/50" />
                                <textarea 
                                    rows={8} 
                                    className="w-full bg-slate-950/50 border border-slate-700/50 rounded-2xl pl-12 pr-6 py-4 text-sm text-slate-200 focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 outline-none leading-relaxed transition-all resize-y"
                                    value={summary}
                                    onChange={(e) => setSummary(e.target.value)}
                                />
                            </div>
                        </div>
                    </div>

                    <div className="flex justify-end gap-4 pt-6 border-t border-slate-700/50">
                        <button className="px-6 py-3 text-xs font-black text-slate-400 uppercase tracking-widest hover:text-white transition-colors">Discard</button>
                        <button onClick={handlePublish} disabled={submitting} className="px-8 py-3 text-xs font-black uppercase tracking-widest bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-500 hover:to-purple-500 text-white rounded-xl shadow-[0_0_20px_rgba(79,70,229,0.4)] transition-all flex items-center gap-2">
                            {submitting ? <Loader2 className="w-4 h-4 animate-spin" /> : <Send className="w-4 h-4" />} 
                            {submitting ? 'Publishing...' : 'Publish & Distribute'}
                        </button>
                    </div>
                </div>
            )}

            {reportStatus === 'published' && (
                <div className="bg-slate-900/40 border border-emerald-500/30 rounded-3xl p-16 text-center shadow-[0_0_30px_rgba(52,211,153,0.1)] relative overflow-hidden animate-fade-in">
                    <div className="absolute inset-0 bg-gradient-to-b from-emerald-500/5 to-transparent"></div>
                    <div className="relative z-10">
                        <div className="w-24 h-24 bg-emerald-500/10 border border-emerald-500/30 rounded-full flex items-center justify-center mx-auto mb-6 relative shadow-[0_0_30px_rgba(52,211,153,0.2)]">
                            <CheckCircle2 className="w-12 h-12 text-emerald-400 relative z-10" />
                        </div>
                        <h3 className="text-2xl font-black text-emerald-400 tracking-tight mb-3">Report Successfully Published</h3>
                        <p className="text-slate-400 text-sm max-w-md mx-auto mb-8 leading-relaxed">
                            The daily progress report has been saved to the permanent archive and distributed to authorized project stakeholders.
                        </p>
                        <div className="flex justify-center gap-4">
                            <button 
                                onClick={() => handleDownloadPDF()}
                                className="bg-slate-800 hover:bg-slate-700 text-white px-6 py-3 rounded-xl text-xs font-black uppercase tracking-widest flex items-center gap-2 transition-colors border border-slate-700"
                            >
                                <Download className="w-4 h-4" /> Download PDF
                            </button>
                            <button onClick={() => setReportStatus('none')} className="bg-emerald-600 hover:bg-emerald-500 text-white px-6 py-3 rounded-xl text-xs font-black uppercase tracking-widest transition-all shadow-[0_0_15px_rgba(52,211,153,0.3)]">
                                Done
                            </button>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}
