-- Add CLIENT_USER to valid_role constraint
ALTER TABLE users DROP CONSTRAINT IF EXISTS valid_role;
ALTER TABLE users ADD CONSTRAINT valid_role CHECK (role IN ('ADMIN', 'USER', 'AUDITOR', 'OPERATIONS', 'ANALYST', 'FIELD_OPERATOR', 'SENIOR_INSPECTOR', 'CLIENT_USER'));
